---
- name: Create Azure VM
  hosts: localhost
  tasks:

  - name: Create virtual network
    azure.azcollection.azure_rm_virtualnetwork:
      resource_group: automation-deploy-rg
      name: vNet
      address_prefixes: "10.0.0.0/16"

  - name: Add subnet
    azure.azcollection.azure_rm_subnet:
      resource_group: automation-deploy-rg
      name: subnet
      address_prefix: "10.0.1.0/24"
      virtual_network: vNet

  - name: Create public IP address
    azure.azcollection.azure_rm_publicipaddress:
      resource_group: automation-deploy-rg
      allocation_method: Static
      name: pip
    register: output_ip_address

  - name: Output public IP
    debug:
      msg: "The public IP is {{ output_ip_address.state.ip_address }}"
  
  - name: Create Network Security Group
    azure.azcollection.azure_rm_securitygroup:
      resource_group: automation-deploy-rg
      name: automation-deploy-rg-networkSecurityGroup
      rules:
        - name: 'allow_rdp'
          protocol: Tcp
          destination_port_range: 3389
          access: Allow
          priority: 1001
          direction: Inbound
        - name: 'allow_web_traffic'
          protocol: Tcp
          destination_port_range:
            - 80
            - 443
          access: Allow
          priority: 1002
          direction: Inbound
        - name: 'allow_powershell_remoting'
          protocol: Tcp
          destination_port_range: 
            - 5985
            - 5986
          access: Allow
          priority: 1003
          direction: Inbound

  - name: Create a network interface
    azure.azcollection.azure_rm_networkinterface:
      name: nic
      resource_group: automation-deploy-rg
      virtual_network: vNet
      subnet_name: subnet
      security_group: automation-deploy-rg-networkSecurityGroup
      ip_configurations:
        - name: default
          public_ip_address_name: pip
          primary: True

  - name: Create VM
    azure.azcollection.azure_rm_virtualmachine:
      resource_group: automation-deploy-rg
      name: win-vm
      vm_size: Standard_DS1_v2
      admin_username: azureuser
      admin_password: Welkom01!
      network_interfaces: nic
      os_type: Windows
      image:
          offer: WindowsServer
          publisher: MicrosoftWindowsServer
          sku: 2019-Datacenter
          version: latest
    no_log: false
