---
- name: Test resource group creation
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    azure_credentials:
      client_id: "<your-client-id>"
      secret: "<your-client-secret>"
      tenant: "<your-tenant-id>"
      subscription_id: "<your-subscription-id>"
    vm_parameters:
      resource_group: "automation-rg"
  tasks:
    - name: Create resource group if not exists
      azure.azcollection.azure_rm_resourcegroup:
        name: "{{ vm_parameters.resource_group }}"
        location: "westeurope"
